### ISSUE TITLE
No Issue Banners on android phone (info request)

### ISSUE THREAD

**Issue by edouardbrasier** [jeffposnick/create-react-pwa#10]
Hi,

I have tried the great "create-react-pwa" to build an app that will work on my phone.
Do you know how many times should I visit the app in order for my android phone to suggest to add the banner for a quick launch from the home screen?
Did I do something wrong see my url below?
https://myhousewealth.firebaseapp.com

The example provided in the document https://jeffy.info/create-react-pwa/ installed the icon banner after just a few visits but no luck with my app.

Many thanks

Ed

**Comment by dtt101** [comment]
@edouardbrasier - I would suggest using https://developers.google.com/web/tools/lighthouse/ to generate a report against your app and fixing the issues it raises. I do not know the exact threshold but I see the banner with scores of around over 75, though it may depend on a combination of test results rather than an overall score.

There are also specific docs on the banner here: https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/

**Comment by jeffposnick** [comment]
Chrome 58 (the current [Canary build](https://www.google.com/chrome/browser/canary.html)) has a new chrome://site-engagement/ page that you could visit, and will give you information about the metric used to trigger the Add to Homescreen banner.
