### ISSUE TITLE
DOMException: unsupported MIME type for service worker

### ISSUE THREAD

**Issue by Boscop** [jeffposnick/create-react-pwa#11]
I did `npm start` on this but i get:
`Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').`
What am I doing wrong?
The file build/service-worker.js exists.
If I copy it to /build or /src I don't get that error. 
Where is the correct location for the file?

**Comment by jeffposnick** [comment]
That's expected, and my apologies that this can be confusing.

In a development environment, you traditionally won't want a service worker installed (since local caching can mess up your ability to iterate on code changes), so there isn't one generated. The local dev HTTP server responds to the request for `/servrice-worker.js` generated from the service worker registration with a HTML error document, leading to that message being logged in the console. This error can be safely ignored.

`npm run build` will generate the production deployment, including a `service-worker.js` in the correct location.

I'll leave this bug open to track added better guidance about this to the docs and inline comments.

**Comment by SamiTriki** [comment]
Hey guys, one way would be to move the service worker registration to the `index.js` or somewhere else and only register it on production environment: 

```javascript
if ('serviceWorker' in navigator && process.env.NODE_ENV === 'production') {
    window.addEventListener('load', function() {
        navigator.serviceWorker.register('/service-worker.js');
    });
}
```

Thoughts ?

**Comment by jeffposnick** [comment]
That's a good point; see also https://github.com/jeffposnick/create-react-app/pull/1, where that approach is being used. If that PR doesn't go anywhere for some reason, then I will add in the same approach into this repo.

**Comment by taverasmisael** [comment]
I was facing the same issue, don't know if it's your case, but I moved the `sw.js` to the root of the public folder and it worked perfectly. Hope it helps.

**Comment by salomao-rodrigues** [comment]
I was having the same issue, not using this tool `create-react-pwa` tool though.
Solved it by adding `%PUBLIC_URL%` to
```javascript
navigator.serviceWorker.register('%PUBLIC_URL%/service-worker.js');`
```
This is because I didn't have the `/` before the path so it would fail to resolve when not in the home page.

**Comment by jeffposnick** [comment]
I'd recommend switching over to the official https://github.com/facebookincubator/create-react-app project, which supports the same functionality now and will be updated moving forward.

**Comment by salomao-rodrigues** [comment]
Yeah sorry, came here from google, didn't realise it was deprecated.
This issue page might still help a lot of people that are in the same situation.
Thanks for the work @jeffposnick

**Comment by ghost** [comment]
add content-type:text/javascript; charset=UTF-8 in response header

**Comment by afloury** [comment]
Hi, I know that it's not exactly the good place for that but it's the first link about PWA on this problem `Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').`

I get the same error working with SSR PWA in VueJS and it take me a lot of time to find the problem so I share my solution to people in same case:
I use the module [sw-precache-webpack-plugin](https://www.npmjs.com/package/sw-precache-webpack-plugin) and to avoid the error in SSR we need this line in server.js :
`app.use('/service-worker.js', serve('./public/service-worker.js'))`

Hope it helps someone !

**Comment by maxtotheguenther** [comment]
Hey, im pretty new in figuring out how to manage react to be compatibel with Workbox as my Serviceworker. What i want is to achieve a running Serviceworker while in a development environment.
I set up my app with create-react-app and added an manifest.json

**Comment by davidsonsns** [comment]
If you are using s3's cloudfront, access your `service-worker.js` file and in the properties change the metadata to `Key: Content-Type Value: application/javascript`

tks @extsalt

**Comment by sayhicoelho** [comment]
if you're using EJS, you can use:
```html
<% if (process.env.NODE_ENV == 'production'){ %>
  <script>
    (function () {
      if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register('/service-worker.js').then(response => {
          console.log('Service Worker registered.')
        }).catch(error => {
          console.error(error)
        })
      }
    })()
  </script>
<% } %>
```

**Comment by oscarabcorona** [comment]
React: 
 public/index.html
```javascript 
<script> 
        if ('serviceWorker' in navigator) {
          window.addEventListener('sw-cached-site.js', function() {
            navigator.serviceWorker.register('service-worker.js', {
              scope: '/',
            });
          });
        } 
        window.process = { env: { NODE_ENV: 'production' } };
     </script>
```

Note: Full app/site
public/sw-cached-site.js

```javascript 
const cacheName = 'v1'; 
self.addEventListener('activate', (e) =>{
  e.waitUntil(
    caches.keys().then(cacheNames => {
      return Promise.all(
        cacheNames.map(cache => {
          if(cache !== cacheName) { 
            return caches.delete(cache);
          }
        })
      )
    })
  )
});
self.addEventListener('fetch', e => { 
  e.respondWith(
      fetch(e.request)
        .then(res => {
            const resClone = res.clone();
            caches
                .open(cacheName)
                .then(cache => {
                    cache.put(e.request, resClone);
                }); 
                return res;
        }).catch(err => caches.match(e.request).then(res => res))
  );
});
```

**Comment by BernhardSmuts** [comment]
> I was facing the same issue, don't know if it's your case, but I moved the `sw.js` to the root of the public folder and it worked perfectly. Hope it helps.

Works perfectly!

**Comment by okafohenry** [comment]
I had this problem trying to implement push notification for my React web app, I fixed it by changing my serviceWorker reference from `serviceWorker` to `service-worker` as in  `navigator.serviceWorker.register('./service-worker.js')` instead of `navigator.serviceWorker.register('./serviceWorker.js')`

**Comment by rajchandra3** [comment]
here is how I solved it, removed `process.env.NODE_ENV === 'production'` condition from `if (process.env.NODE_ENV === 'production' && 'serviceWorker' in navigator) {`

Fix the issue for me, i am aware of the implications of registering service worker in development but it works for me this way.

**Comment by Harshit2929** [comment]
In your script file where you are registering your service worker,in the function instead of using:
![image](https://user-images.githubusercontent.com/56792415/110580708-31c17300-818f-11eb-9f96-9f1873adb5a1.png)

Use this:
![image](https://user-images.githubusercontent.com/56792415/110580773-5289c880-818f-11eb-8be9-acf3dfb030c3.png)
here are my code for  files index.html ,sw.js(in public folder) and main.js (in src folder):
->index.html
![image](https://user-images.githubusercontent.com/56792415/110581009-bd3b0400-818f-11eb-9b16-2eaeebb15f0d.png)
->sw.js
![image](https://user-images.githubusercontent.com/56792415/110581078-e065b380-818f-11eb-8f1f-ff2c3346cc3b.png)
->main.js
![image](https://user-images.githubusercontent.com/56792415/110581147-fbd0be80-818f-11eb-8366-0d2c02ad9321.png)
->My files:
![image](https://user-images.githubusercontent.com/56792415/110581345-5833de00-8190-11eb-97d8-f6d5a407b582.png)
It works now 🤩
![image](https://user-images.githubusercontent.com/56792415/110581513-b19c0d00-8190-11eb-8671-0d8daaaf4865.png)
